export const queryKeys = {
  categories: ['admin', 'categories'] as const,
  products: ['admin', 'products'] as const,
  tables: ['admin', 'tables'] as const,
  orders: ['admin', 'orders'] as const,
  settings: ['admin', 'settings'] as const,
  ingredients: ['admin', 'inventory', 'ingredients'] as const,
  stockMovements: ['admin', 'inventory', 'movements'] as const,
  stockAlerts: ['admin', 'inventory', 'alerts'] as const,
  cmvReport: (from?: string, to?: string) => ['admin', 'inventory', 'cmv', from, to] as const,
  productRecipe: (productId: string) => ['admin', 'inventory', 'recipe', productId] as const,
  whatsappConnection: ['admin', 'whatsapp', 'connection'] as const,
  financeDashboard: (from?: string, to?: string) => ['admin', 'finance', 'dashboard', from, to] as const,
  financeDre: (from?: string, to?: string) => ['admin', 'finance', 'dre', from, to] as const,
  financeExpenses: (from?: string, to?: string) => ['admin', 'finance', 'expenses', from, to] as const,
  financeCashClosing: (date?: string) => ['admin', 'finance', 'cash-closing', date] as const,
  menuTable: (token: string) => ['menu', 'table', token] as const,
  menuDelivery: (slug: string) => ['menu', 'delivery', slug] as const,
  kitchenOrders: ['kitchen', 'orders'] as const,
};
